platform :ios, '8.0'
# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

target 'RuntimeTest' do
    pod 'lottie-ios', '~> 2.1.4'
    pod 'TYAttributedLabel', '~> 2.6.2'
    pod 'SDWebImage', '~> 4.2.1'
    pod 'JPFPSStatus', '~> 0.1.1'
    #     pod 'Masonry', '~> 1.1.0'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'GPUImage', '~> 0.1.7'
#    pod 'YYCache', '~> 1.0.4'
    pod 'FJAlertView', '~> 0.0.4'
    #     pod 'FTLinearActivityIndicator', '~> 1.0.4'
    pod 'JPush', '~> 3.0.8'
#    pod 'Moya', '~> 11.0.1'
end
