# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
# use_frameworks!

target 'RuntimeTest' do
     pod 'lottie-ios', '~> 2.1.4'
     pod 'TYAttributedLabel', '~> 2.6.2'
     pod 'SDWebImage', '~> 4.2.1'
end
